buildspec.yml
docker/1.1.0/final/Dockerfile.cpu
docker/1.1.0/final/Dockerfile.gpu
setup.py
test/conftest.py
test/utils/image_utils.py

Add PY2 support

---

test/integration/sagemaker/test_mnist.py

1. Specify named argument for image and sagemaker_session for PyTorchModel, else it fails with:
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateModel operation: Region of "763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:1.2.0-gpu-py2" does not match expected region of us-east-1. Cross region ECR image pulls are not allowed.
```
2. The sagemaker_session parameter was used in place of where the py_version was being expected, as shown here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/pytorch/model.py#L63
Test Results
```
[ec2-user@ip-172-31-30-85 sagemaker-pytorch-serving-container]$ pytest test/integration/sagemaker/test_mnist.py --aws-id 763104351884 --region us-west-2 …
```

Specify named arguments for PyTorchModel in test_mnist

---

buildspec.yml

related:
* https://github.com/aws/sagemaker-mxnet-serving-container/pull/76
* https://github.com/aws/sagemaker-mxnet-container/pull/113
* https://github.com/aws/sagemaker-chainer-container/pull/107
* https://github.com/aws/sagemaker-pytorch-container/pull/134

change: use regional endpoint for STS in builds

---

buildspec.yml
docker/1.3.1/py2/Dockerfile.cpu
docker/1.3.1/py3/Dockerfile.cpu
setup.py

- bump sagemaker-inference-toolkit version to 1.1.2
- add mme capability label to 1.3.1 dockerfiles

change: bump inference-toolkit version and add mme label

---

docker/1.2.0/py2/Dockerfile.cpu
docker/1.2.0/py2/Dockerfile.gpu
docker/1.2.0/py3/Dockerfile.cpu
docker/1.2.0/py3/Dockerfile.gpu
docker/1.3.1/py2/Dockerfile.cpu
docker/1.3.1/py2/Dockerfile.gpu
docker/1.3.1/py3/Dockerfile.cpu
docker/1.3.1/py3/Dockerfile.gpu

Dockerfiles for PyTorch Serving 1.2.0 and 1.3.1 were missing LABEL to accept sagemaker bind-to-port capability.

Add LABEL for port bind to 1.2.0 and 1.3.1 dockerfiles

---

setup.py

`PyTorch.LATEST_VERSION` has been updated, so upgrading the library dependency here.

change: upgrade sagemaker to 1.48.0 for test dependencies

---

.gitignore

`test/resources/local_mode_lock` is specific to our integ tests, `.tox/` and `.coverage` are for our tox stuff, and `*.egg-info/` and `__pycache__/` are Python-specific. The two existing entries are actually not project-specific and should be in a person's global gitignore if it applies to them (i.e. if they use a Mac and/or an IDEA product), but I thought it would be easier to just leave them alone.

change: update gitignore

---

src/sagemaker_pytorch_serving_container/__init__.py
src/sagemaker_pytorch_serving_container/deep_learning_container.py
src/sagemaker_pytorch_serving_container/handler_service.py
src/sagemaker_pytorch_serving_container/serving.py
test/__init__.py
test/conftest.py
test/integration/__init__.py
test/integration/local/__init__.py
test/integration/local/test_serving.py
test/integration/sagemaker/__init__.py
test/integration/sagemaker/test_mnist.py
test/integration/sagemaker/timeout.py
test/resources/call_model_fn_once.py
test/resources/mnist/mnist.py
test/resources/mnist/model_cpu/1d/mnist_1d.py
test/resources/mnist/model_cpu/call_model_fn_once.py
test/resources/mnist/model_cpu/mnist.py
test/resources/mnist/model_gpu/mnist.py
test/unit/test_deep_learning_containers.py
test/unit/test_default_inference_handler.py
test/unit/test_handler_service.py
test/unit/test_serving.py
test/utils/__init__.py
test/utils/image_utils.py
test/utils/local_mode_utils.py

This repo was created in 2019. And also the current year is 2019, so the license headers should acknowledge that anyway. (I realize if I'd wait 12 days I might as well put 2020 😂 )

change: fix year in copyright license header

---

MANIFEST.in
buildspec-deploy.yml
buildspec-release.yml
buildspec.yml
docker/1.3.1/py2/Dockerfile.cpu
docker/1.3.1/py2/Dockerfile.gpu
docker/1.3.1/py3/Dockerfile.cpu
docker/1.3.1/py3/Dockerfile.gpu
setup.py
tox.ini

feature: Add release to PyPI. Change package name to sagemaker-pytorch-inference.

feature: Add release to PyPI. Change package name to sagemaker-pytorch-inference.

---

.gitignore
tox.ini

change: Fix py2 test environment.

change: Fix py2 test environment.

---

docker/1.4.0/py2/Dockerfile.cpu
docker/1.4.0/py2/Dockerfile.gpu
docker/1.4.0/py3/Dockerfile.cpu
docker/1.4.0/py3/Dockerfile.gpu

Update license URL for PyTorch

update: Update license URL

---

setup.py

Remove torch as a requirement for sagemaker_pytorch_inference toolkit

update: Remove torch as requirement for sagemaker_pytorch_inference

---

docker/1.4.0/py3/Dockerfile.cpu
docker/1.4.0/py3/Dockerfile.gpu
test/conftest.py

skip the model_fn_called_once only for 1.4.0 gpu py2

change: undo upgrade mms version and library name

---

setup.py

Upgrade to the latest version of sagemaker-inference: https://github.com/aws/sagemaker-inference-toolkit/releases/tag/v1.2.0

Upgrade the version of sagemaker-inference

---

README.rst

Add PyTorch EIA links, examples in README

doc: update README with pytorch eia section

---

docker/1.4.0/py2/Dockerfile.cpu
docker/1.4.0/py2/Dockerfile.gpu
docker/1.4.0/py3/Dockerfile.cpu
docker/1.4.0/py3/Dockerfile.gpu

Issue #, if available:
Version conflict between awscli 1.18.22 and botocore 1.15.23
Description of changes:
Updated awscli to 1.18.23 for py3 containers

awscli version 1.18.23

---

setup.py

upgrade inference-toolkit version to consume this change: https://github.com/aws/sagemaker-inference-toolkit/pull/44

fix: upgrade inference-toolkit version

---

docker/1.3.1/py3/Dockerfile.eia
docker/1.4.0/py2/Dockerfile.cpu
docker/1.4.0/py2/Dockerfile.gpu
docker/1.4.0/py3/Dockerfile.cpu
docker/1.4.0/py3/Dockerfile.gpu

The line
```
curl -o ~/miniconda.sh -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
```
doesn't work anymore after a change in the way the file is hosted at that URL around April 07, 2020.
Therefore this curl command has been replaced with
```
curl -L -o ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
```
with `curl -L` to allow the link to be redirected to the actual download link.

Change miniconda installation in dockerfiles

---

docker/1.3.1/py3/Dockerfile.eia

PR for EI dockerfile corresponding to #63 

change: Update package versions to fix safety check vulnerabilities

---

src/sagemaker_pytorch_serving_container/default_inference_handler.py

Since the EI-enabled client framework is CPU only, we will load PyTorch models to CPU by default when the user is using Elastic Inference. The model still runs on the server in CUDA

Load EI model to CPU by default in model_fn

---

docker/1.3.1/py3/Dockerfile.eia

Install awscli in PyTorch 1.3.1 EIA dockerfile from pypi instead of conda.

change: Install awscli in 1.3.1 eia from pypi instead of conda

---

buildspec-release.yml
buildspec-toolkit.yml
setup.py
tox.ini

- Upgrade version of sagemaker-inference to `1.3.1`, which supports Python 3.7.
- Update tox and buildspecs to test against py37.
- Update Python version in `setup.py`.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

feature: Python 3.7 support

---

tox.ini

fix: Pin sagemaker dependancy version to before version 2

---

setup.py
src/sagemaker_pytorch_serving_container/torchserve.py
test/unit/test_model_server.py
test/utils/file_utils.py
tox.ini

1. In MME mode, no default model should be loaded. Currently, the torchserve command attempts to load a default 'model' from the path `/opt/ml/models`.
2. This change removes the commandline arg based on whether the container is running in MME mode or not:
**Failure log**
```
2022-09-07T21:03:56.608+02:00   2022-09-07T19:03:55,758 [INFO ] W-9000-model_1.0-stdout MODEL_LOG - model_name: model, batchSize: 1
2022-09-07T21:03:56.608+02:00   2022-09-07T19:03:55,808 [INFO ] W-9000-model_1.0-stdout MODEL_LOG - Backend worker process died.
2022-09-07T21:03:56.608+02:00   2022-09-07T19:03:55,808 [INFO ] W-9000-model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-09-07T21:03:56.608+02:00   2022-09-07T19:03:55,809 [INFO ] …
```

Fix: Don't load default model in MME mode

---

src/sagemaker_pytorch_serving_container/etc/log4j2.xml
src/sagemaker_pytorch_serving_container/torchserve.py

Creating PR to update Pytorch Inference toolkit to log telemetry metrics in case of failure.
TorchServe PR: https://github.com/pytorch/serve/pull/1974
Telemetry Design Doc: https://quip-amazon.com/8hW4AJQQu4Na/Inference-Telemetry-Failure-rate-low-level-design
Please refer to this document for more details about the PR: https://quip-amazon.com/VMoqANQATkNH/Code-Changes-in-TorchServe-and-PyTorch-Inference-Toolkit-to-Log-Telemetry-Metrics
Example code block for logging telemetry metrics:
```
loggerTelemetryMetrics.info("ModelServerError.Count:1|#TorchServe:{},{}:-1", ConfigManager.getInstance().getVersion(), "error");
```
Sample output:
```
ModelServerError.Count:1|#TorchServe:0.6.1,error:-1
ModelServerError.Count:1|#TorchServe:0.6.1,error:-1 …
```

Update PyTorch Inference toolkit to log telemetry metrics

---

src/sagemaker_pytorch_serving_container/etc/default-ts.properties
src/sagemaker_pytorch_serving_container/etc/mme-ts.properties
tox.ini

#99 
Apply the [fixing](https://github.com/aws/sagemaker-inference-toolkit/pull/87) in pytorch inference toolkit

add vmargs=-XX:-UseContainerSupport in config

---

src/sagemaker_pytorch_serving_container/torchserve.py
test/unit/test_model_server.py

*Issue #, if available: #149
use the `REQUIREMENTS_PATH` and `_install_requirements()` from `sagemaker-inference-toolkit` to get CodeArtifact support for free from https://github.com/aws/sagemaker-inference-toolkit/pull/130 and to reduce code duplication

reuse sagemaker-inference's requirements.txt installation logic

---

buildspec-release.yml
buildspec.yml
setup.py
src/sagemaker_pytorch_serving_container/default_pytorch_inference_handler.py
test/conftest.py
test/container/2.0.0/Dockerfile.dlc.cpu
test/container/2.0.0/Dockerfile.dlc.gpu
test/container/2.0.1/Dockerfile.dlc.cpu
test/container/2.0.1/Dockerfile.dlc.gpu
test/integration/local/test_serving.py
test/integration/sagemaker/test_default_inference.py
test/integration/sagemaker/test_mnist.py
test/resources/mnist/model_gpu/code/mnist.py
tox.ini

**Note**: For more details about changes in SageMaker Python SDK from v1 to v2, please refer to this [link](https://sagemaker.readthedocs.io/en/stable/v2.html).
The following files need to be updated:
- [setup.py](https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/master/setup.py): 
- Update the `classifiers` in `setup` to update the Python versions to Python 3.8, 3.9 and 3.10.
- Update the test dependencies to use later versions and remove `sagemaker-containers`.
- test/container/2.0.1/:
- Create a CPU DLC Dockerfile with the PyTorch 2.0.1 TorchServe SageMaker DLC image and install the PyTorch inference toolkit binary (similar to [test/container/1.10.2/Dockerfile.dlc.cpu](https://github.com/aws/sagemaker-pytorch-inference-too …

Fix integration tests and update Python versions

---

buildspec.yml
setup.py
tox.ini

Creating PR to fix dependency versions in `setup.py` and `tox.ini`

Fix dependency versions

---

src/sagemaker_inference/transformer.py

Issue #163
Improve debuggability during model load and inference failures caused by custom handler method implementation.
This is done by logging the exception traceback in addition to sending the traceback in the response back to client. Although this trackback is sent back to the client in the response body, the client may sometimes fail to load entire response body, for ex:
`
botocore.errorfactory.ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary and could not load the entire response body. See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-pytorch-serving-**********-**** in account ************ for …

Improve error logging when invoking custom handler methods

---

buildspec.yml
src/sagemaker_pytorch_serving_container/torchserve.py
test/conftest.py
test/container/2.1.0/Dockerfile.dlc.cpu
test/container/2.1.0/Dockerfile.dlc.gpu
test/container/2.2.0/Dockerfile.dlc.cpu
test/container/2.2.0/Dockerfile.dlc.gpu
test/integration/sagemaker/test_multi_model_endpoint_sagemaker.py

When checking to see if the TorchServe process is running, we iterate through the current list of running processes using `psutil`:
https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/36a842e374766a088f21906ce17496e88a140a1b/src/sagemaker_pytorch_serving_container/torchserve.py#L183-L188
Calling the `command()` psutil API on a zombie process raises the `psutil.ZombieProcess` exception. This unhandled exception causes TorchServe to be stopped which is not expected behavior in DLC: https://github.com/aws/deep-learning-containers/tree/master/pytorch/inference
```
File "/opt/conda/lib/python3.10/site-packages/sagemaker_pytorch_serving_container/torchserve.py", line 187, in _retrieve_ts_server_process
if TS_NAMESPACE in process.cmdline():
File …
```

Ignore zombie processes when detecting TorchServe status

---

src/sagemaker_pytorch_serving_container/etc/default-ts.properties
src/sagemaker_pytorch_serving_container/etc/mme-ts.properties

Disabling token auth and enabling model API by default for DLC since access to the endpoint will be restricted by IAM.

Disabling token auth and enabling model API by default
